### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by KatieFelidae** [Kolossi/GmmkUtil#2]
Been getting this error recently:

`Error:
  An assembly specified in the application dependencies manifest (GmmkUtilConsole.deps.json) was not found:
    package: 'Microsoft.Win32.SystemEvents', version: '4.7.0'
    path: 'runtimes/win/lib/netcoreapp3.0/Microsoft.Win32.SystemEvents.dll'`

Running Windows 10 Pro 21H1

Tried to downgrade or install alongside Microsoft.Win32.SystemEvents 4.7.0, but it's still occurring.

**Comment by Kolossi** [comment]
Definitely only the .exe is needed, copying dlls around not required, but the PC will have to have a dotnetcore runtime >=v3.0 installed.

Go to a command prompt and issue
```
dotnet --list-runtimes
```

Is there an entry
```
Microsoft.NETCore.App 3.1.x [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
```

For some `x` (path may differ)

?

On Windows 10 it should be on there, but can be removed or corrupted?

**Comment by Kolossi** [comment]
The app is also untouched for a long time.

It prob needs updating to latest dotnet and update all packages including the device.net library.

I had a quick try but device.net v4.x seems to be a breaking change to the current v3.x used here.

I'll try to look at updating the code before long.

**Comment by KatieFelidae** [comment]
Running that command gave me:
```
Microsoft.AspNetCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 3.1.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
I ran it through Visual Studio and added 5.0.8 as the dotnet version and made a build. It's messy, but it's working for me as is. This little piece of software keeps my desk dark at night and it's literally a lifesaver.

**Comment by Kolossi** [comment]
Glad you've found some use for this software @katieklapach 

I've updated to dotnet 5.0, and created a new release which is a single self-contained exe - [v0.2.1-alpha](https://github.com/Kolossi/GmmkUtil/releases/tag/v0.2.1-alpha)

I haven't updated to device.net v4.x as I couldn't quickly figure the changes needed, and unless I hear otherwise, I believe this is working fine with v3.x.

I hope the new exe allows you to easily keep your desk dark when it should be, please let me know if it does the job. :-)

**Comment by KatieFelidae** [comment]
Works perfectly! Amazing job!

**Comment by Kolossi** [comment]
Good news. :-)

Any other issues, post back.
